name: deploy Erp app

on:
  push:
    branches: [ "main" ]

jobs:
  deploy-erp:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
            
    - name: Deploy to the server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        timeout: 1700s
        
        script: |
            # installing docker
            # sudo apt-get update && sudo apt-get install docker.io -y

            # installing git
            # sudo apt-get install git -y

            # clone the project
            # git clone https://github.com/Erpnext-Setup/erpnext14-with-github-actions.git

            # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition
            # sudo sysctl vm.overcommit_memory=1

            # navigate toe cloned repoo
            cd erpnext14-with-github-actions
           
            # CREATE NETWORK
            # docker network create erpnet

            # RUN MARIADB CONTAINER
            docker run -it  --net erpnet --name erpdb -e MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD -v $(pwd)/conf:/etc/mysql/conf.d -d 1devops2/erpnext14-with-github-actions:db
            sleep 10

            # RUN FRAPPE-APP CONTAINER
            docker run -it --network erpnet --name erp -p 8000:8000 -p 9000:9000 -p3306:3306 -d 1devops2/erpnext14-with-github-actions:app
            sleep 10

            docker exec erp bash -c " 
            cd frappe-bench && \
            bench new-site $APP_SITE_NAME --admin-password '$ADMIN_PASSWORD' --mariadb-root-username $MYSQL_ROOT_USER --mariadb-root-password $MYSQL_ROOT_PASSWORD --db-host erpdb && \
            bench --site $APP_SITE_NAME install-app erpnext && \
            bench get-app branch version-14 https://github.com/yrestom/POS-Awesome.git && \
            bench setup requirements && \
            bench build --app posawesome && \
            bench --site $APP_SITE_NAME install-app posawesome && \
            cd /home/frappe/frappe-bench/sites && echo "$APP_SITE_NAME" >currentsite.txt && \
            cd /home/frappe/frappe-bench && screen -dmS bench_session bash -c 'bench start' && \
            exit "

            # url access point
            echo "ERP app is deployed. you can access at http://$APP_SITE_NAME:8000"
            sleep 5
            
            # exit the machine
            exit
      env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_ROOT_USER: ${{ secrets.MYSQL_ROOT_USER }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
          APP_SITE_NAME: ${{ secrets.ERP_SITE_NAME }}
          ERP_SITE_HOST: ${{ secrets.SSH_HOST }}


    - name: cleanup
      run: rm -rf ~/.ssh
